apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-orbit-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: star-orbit
  template:
    metadata:
      labels:
        app: star-orbit
    spec:
      containers:
      - name: star-orbit-container
        image: hasebul21/star-orbit-app:latest # Use your actual Docker Hub image
        ports:
        - containerPort: 80