apiVersion: v1
kind: Service
metadata:
  name: star-orbit-service
  namespace: default
spec:
  selector:
    app: star-orbit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Use ClusterIP for local testing, or LoadBalancer if using Minikube/Docker Desktop